version: '3.8'

services:
  gigachat-api:
    build: .
    ports:
      - "8006:8006"
    environment:
      - GIGACHAT_CLIENT_ID=6e34424e-3690-4c2e-92c0-5db1f3f831cb
      - GIGACHAT_CLIENT_SECRET=NmUzNDQyNGUtMzY5MC00YzJlLTkyYzAtNWRiMWYzZjgzMWNiOmMyMWUxYmI4LTU3ZTYtNDI0Ni04YWQ0LTIyNTFjZTk1OWYyYQ==
      - GIGACHAT_SCOPES=GIGACHAT_API_PERS
    volumes:
      - ./.env:/app/.env
